---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: EC2NodeClass
metadata:
  name: example-ec2nodeclass
spec:
  subnetSelector:
    karpenter.sh/discovery: Demo-dev-app-eks
  securityGroupSelector:
    karpenter.sh/discovery: Demo-dev-app-eks
  instanceProfile: KarpenterNodeInstanceProfile
  instanceTypes:
    - m5.large
    - m5.xlarge
---
apiVersion: karpenter.sh/v1alpha5
kind: NodePool
metadata:
  name: example-nodepool
spec:
  template:
    spec:
      nodeClass:
        kind: EC2NodeClass
        name: example-ec2nodeclass
      capacityType: spot
      taints:
        - key: example-taint
          value: example-value
          effect: NoSchedule
      labels:
        example-label: example-value
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
      limits:
        resources:
          cpu: "1000"
          memory: 1000Gi
